products/urls.py
from products import views
from django.conf.urls import url

from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required


app_name = 'products'

urlpatterns = [

    url(r'addProduct/$', login_required(views.AddProductView.as_view()), name='addProduct'),
    url(r'viewProduct/$', login_required(views.FullProductView.as_view()), name='viewProduct'),
    #url for product backlog
    url(r'^viewPBI/', login_required(views.PBIView.as_view()), name='viewPBI'),
    url(r'addPBI', login_required(views.AddPBIView.as_view()), name='addPBI'),
    url(r'viewFullPBI', login_required(views.FullPBIView.as_view()), name='veiwFullPBI'),
    url(r'^deletePBI/(?P<pk>\d+)/$',login_required(views.DeletePBIView.as_view()), name='deletePBI'),
    url(r'updatePBI/(?P<pk>\d+)/$', login_required(views.EditPBIView.as_view()), name='editPBI'),
    url(r'^viewPBIdetail/(?P<pk>\d+)/$', login_required(views.PBIDetailView.as_view()), name='pbiDetail'),
    url(r'^addtoSprint/(?P<pk>\d+)/$', login_required(views.addtoSprint.as_view()), name='addtoSprint'),

    #url for sprint backlog
    url(r'^sprintBacklog/$', login_required(views.SprintBacklogView.as_view()), name='sprintBacklog'),
    url(r'^fullSprintBacklog/$', login_required(views.FullSprintBacklogView.as_view()), name='fullSprintBacklog'),
    url(r'addTask', login_required(views.AddTaskView.as_view()), name='addTask'),
    url(r'^updateTask/(?P<pk>\d+)/$', login_required(views.EditTaskView.as_view()), name='editTask'),
    url(r'^deleteTask/(?P<pk>\d+)/$', login_required(views.DeleteTaskView.as_view()), name='deletePBI'),
    url(r'^viewTASKdetail/(?P<pk>\d+)/$', login_required(views.TaskDetailView.as_view()), name='taskDetail'),
    url(r'^profile/$', login_required(views.profile),name='profile'),

    url(r'^$', auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name='logout.html'),name='logout'),
    url(r'^register$',views.registerView, name='register'),
    url(r'^registerdev/$',views.DevRegisterView, name='devregister'),
    url(r'^registersm/$',views.SMRegisterView, name='smregister'),
    url(r'^registerpo/$',views.PoRegisterView, name='poregister'),



    url(r'^changeSprint/$', login_required(views.ChangeSprintView.as_view()), name='changeSprint'),

]

scrum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from products import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('products.urls')),
]

templates/add_pbi.html
<!DOCTYPE html>
<html lang="en">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% load static %}
<link href="{% static 'css/addproduct.css'%}" rel="stylesheet">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Simple Sidebar - Start Bootstrap Template</title>


  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">

</head>

<body>

  <div class="d-flex" id="wrapper">
    <div class="bg-light border-right" id="sidebar-wrapper">
    {% include 'header.html' %}

    <!-- Page Content -->
    <div id="page-content-wrapper">

      {% include 'navbar.html' %}

      <div class="container-fluid">
        <h1 class="mt-4"> </h1>


        <div class="container register-form">
                    <div class="form">
                        <div class="note">
                            <p>Create a new PBI.</p>
                        </div>

                        <form class="form-content" method="post">

                          {% csrf_token %}
                          {{form.as_p}}
                          <button class="btn btn-primary">Submit</button>

                        </form>
                    </div>
                </div>



      </div>
    </div>
    </div>
    <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->


  <!-- Bootstrap core JavaScript -->
  <script src= "{% static 'vendor/jquery/jquery.min.js' %}" ></script>
  <script src= "{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>

</body>

</html>



<!------ Include the above in your HEAD tag ---------->

templates/add_task.html
<!DOCTYPE html>
<html lang="en">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% load static %}
<link href="{% static 'css/addproduct.css'%}" rel="stylesheet">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Simple Sidebar - Start Bootstrap Template</title>


  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">

</head>

<body>

  <div class="d-flex" id="wrapper">
    <div class="bg-light border-right" id="sidebar-wrapper">
    {% include 'header.html' %}

    <!-- Page Content -->
    <div id="page-content-wrapper">

      {% include 'navbar.html' %}

      <div class="container-fluid">
        <h1 class="mt-4"> </h1>


        <div class="container register-form">
                    <div class="form">
                        <div class="note">
                            <p>Create a new Task.</p>
                        </div>

                        <form class="form-content" method="post">

                          {% csrf_token %}
                          {{form.as_p}}
                          <button class="btn btn-primary">Submit</button>

                        </form>
                    </div>
                </div>



      </div>
    </div>
    </div>
    <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->


  <!-- Bootstrap core JavaScript -->
  <script src= "{% static 'vendor/jquery/jquery.min.js' %}" ></script>
  <script src= "{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>

</body>

</html>



<!------ Include the above in your HEAD tag ---------->

templates/add_to_Sprint.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Simple Sidebar - Start Bootstrap Template</title>
  {% load static %}

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">

</head>

<body>

  <div class="d-flex" id="wrapper">

    <div class="bg-light border-right" id="sidebar-wrapper">
    {% include 'header.html' %}

    <!-- Page Content -->
    <div id="page-content-wrapper">

      {% include 'navbar.html' %}

      <form action="" method="post">
        {% csrf_token %}
        <blockquote class="blockquote text-center">
            {% if PBI.in_sprint == False %}
                <p class="mb-0">Add this PBI "{{PBI.name}}" to sprint?</p>
            {% else %}
                <p class="mb-0">Uncheck the box to remove this PBI </p>
                <p class="mb-0">Remove this PBI "{{PBI.name}}" from sprint?</p>
            {% endif %}
              {{ form.as_p }}
              <input type="submit" value="Update">


        </blockquote>
      </form>

    </div>
    </div>
    <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->


  <!-- Bootstrap core JavaScript -->
  <script src= "{% static 'vendor/jquery/jquery.min.js' %}" ></script>
  <script src= "{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>

</body>

</html>

templates/chang_sprint.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Simple Sidebar - Start Bootstrap Template</title>
  {% load static %}

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">

</head>

<body>

  <div class="d-flex" id="wrapper">

    <div class="bg-light border-right" id="sidebar-wrapper">
    {% include 'header.html' %}

    <!-- Page Content -->
    <div id="page-content-wrapper">

    {% include 'navbar.html' %}
    

    </div>
    </div>
    <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->


  <!-- Bootstrap core JavaScript -->
  <script src= "{% static 'vendor/jquery/jquery.min.js' %}" ></script>
  <script src= "{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script>
    function redirect(){
       window.location.href = "{% url 'products:sprintBacklog' %}";
    }

    setTimeout(redirect, 0); //2000 is equivalent to 2 seconds
</script>
  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>

</body>

</html>

templates/detail_pbi.html


<!DOCTYPE html>
<html lang="en">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% load static %}
<link href="{% static 'css/addproduct.css'%}" rel="stylesheet">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Simple Sidebar - Start Bootstrap Template</title>


  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">

</head>

<body>

  <div class="d-flex" id="wrapper">
    <div class="bg-light border-right" id="sidebar-wrapper">
    {% include 'header.html' %}

    <!-- Page Content -->
    <div id="page-content-wrapper">

      {% include 'navbar.html' %}

      <div class="container-fluid">
        <h1 class="mt-4"> </h1>


        <div class="container register-form">
                    <div class="form">
                        <div class="note">
                            <p> Feature Detail</p>

                        </div>

                        <form class="form-content" method="post">

                          <center>
                            <form action="" method="post">
                      {% csrf_token %}
                              <p><b>Feature name: </b> {{PBI.name}} </p>
                              <p><b>Description: </b>{{PBI.description}}</p>
                                <p><b>Priority: </b> {{ PBI.priority }}</p>
                                  <p><b>Estimate of Story Point: </b>{{ PBI.story_point }}</p>
                                  <p><b>Status: </b>{{ PBI.status }}</p>
                                  <div class="btn-group" role="group" aria-label="Basic example">
                                  {% if pbi.status == "NOT_YET_START" %}
                                      <button onclick="window.location.href = 'http://127.0.0.1:8000/viewPBIdetail/{{ PBI.pk }}';">Edit</button>
                                      <button onclick="window.location.href = 'http://127.0.0.1:8000/deletePBI/{{ PBI.pk }}';">Delete</button>
                                  {% endif %}
                                  <input type=button value="Back" onClick="javascript:history.go(-1);">
                                </div>

                            </form>
                          </center>
                        </form>
                    </div>
                </div>



      </div>
    </div>
    </div>
    <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->


  <!-- Bootstrap core JavaScript -->
  <script src= "{% static 'vendor/jquery/jquery.min.js' %}" ></script>
  <script src= "{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>

</body>

</html>



<!------ Include the above in your HEAD tag ---------->

templates/detail_task.html


<!DOCTYPE html>
<html lang="en">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% load static %}
<link href="{% static 'css/addproduct.css'%}" rel="stylesheet">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Simple Sidebar - Start Bootstrap Template</title>


  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">

</head>

<body>

  <div class="d-flex" id="wrapper">
    <div class="bg-light border-right" id="sidebar-wrapper">
    {% include 'header.html' %}

    <!-- Page Content -->
    <div id="page-content-wrapper">

      {% include 'navbar.html' %}

      <div class="container-fluid">
        <h1 class="mt-4"> </h1>


        <div class="container register-form">
                    <div class="form">
                        <div class="note">
                            <p> Task Detail</p>

                        </div>

                        <form class="form-content" method="post">

                          <center>
                            <form action="" method="post">
                      {% csrf_token %}

                        {% csrf_token %}
                          <p><b>PBI: </b> {{task.pbi}} </p>
                        <p><b>Task name: </b> {{task.name}} </p>

                          <p><b>Description: </b> {{ task.description }}</p>
                            <p><b>Hour: </b>{{ task.hour }}</p>
                            <p><b>Status: </b>{{ task.status }}</p>
                            <p><b>Owner: </b>{{ task.owner }}</p>


                                  <input type=button value="Back" onClick="javascript:history.go(-1);">
                                </div>

                            </form>
                          </center>
                        </form>
                    </div>
                </div>



      </div>
    </div>
    </div>
    <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->


  <!-- Bootstrap core JavaScript -->
  <script src= "{% static 'vendor/jquery/jquery.min.js' %}" ></script>
  <script src= "{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>

</body>

</html>



<!------ Include the above in your HEAD tag ---------->

templates/edit_task.html



<!DOCTYPE html>
<html lang="en">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% load static %}
<link href="{% static 'css/addproduct.css'%}" rel="stylesheet">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Simple Sidebar - Start Bootstrap Template</title>


  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">

</head>

<body>

  <div class="d-flex" id="wrapper">
    <div class="bg-light border-right" id="sidebar-wrapper">
    {% include 'header.html' %}

    <!-- Page Content -->
    <div id="page-content-wrapper">

      {% include 'navbar.html' %}

      <div class="container-fluid">
        <h1 class="mt-4"> </h1>


        <div class="container register-form">
                    <div class="form">
                        <div class="note">
                            <p>Update this Task "{{edit.name}}"?</p>

                        </div>

                        <form class="form-content" method="post">

                          {% csrf_token %}
                          {{form.as_p}}
                          <button class="btn btn-primary">Submit</button>

                        </form>
                    </div>
                </div>



      </div>
    </div>
    </div>
    <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->


  <!-- Bootstrap core JavaScript -->
  <script src= "{% static 'vendor/jquery/jquery.min.js' %}" ></script>
  <script src= "{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>

</body>

</html>



<!------ Include the above in your HEAD tag ---------->

templates/header.html
    <div class="sidebar-heading">Product A</div>
      <div class="list-group list-group-flush">
                <a href="http://127.0.0.1:8000/viewProduct" class="list-group-item list-group-item-action bg-light">Products Full view</a>
        <a href="http://127.0.0.1:8000/viewPBI" class="list-group-item list-group-item-action bg-light">Product BackLog</a>
        <a href="http://127.0.0.1:8000/sprintBacklog" class="list-group-item list-group-item-action bg-light">Sprint BackLog</a>

      </div>
    </div>

templates/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
   {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="{% static 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js' %}" charset="utf-8"></script>
  </head>
  <body>




        <div class = "content-section">
          <center>
          <form method="POST" class="login-form">
            <h1>Welcome to BackTrack </h1>

            {%csrf_token %}
            <fieldset class="form-group">
              <legend class="border-bottom mb-4">Login to BackTrack</legend>
                  {{ form.as_p}}
            
                  <center><button class="btn btn-success" type="btn btn-outline-info" name="submit">Login</button></center>

            </fieldset>
              

            <div class="border-top pt-3">
                <small class="text-muted">
                Need An Account? <button class="btn btn-dark" onclick="window.location.href = 'http://127.0.0.1:8000/register';">REGISTER</button>
                </small>
            </div>
              

          </form>
          </center>
        </div>




      <script type="text/javascript">
      $(".txtb input").on("focus",function(){
        $(this).addClass("focus");
      });

      $(".txtb input").on("blur",function(){
        if($(this).val() == "")
        $(this).removeClass("focus");
      });

      </script>


  </body>
</html>

templates/pbi.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Simple Sidebar - Start Bootstrap Template</title>
  {% load static %}

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">

</head>

<body>

  <div class="d-flex" id="wrapper">
    <div class="bg-light border-right" id="sidebar-wrapper">
    {% include 'header.html' %}

    <!-- Page Content -->
    <div id="page-content-wrapper">

      {% include 'navbar.html' %}

      <div class="container-fluid">
        <div>
          <h1 class="mt-4">
            Product BackLog
            <button class="btn btn-primary" onclick="window.location.href = 'http://127.0.0.1:8000/viewFullPBI';">
              Switch to Full View
            </button>
          </h1>
        </div>

        <table class="table">
          <thead class="thead-dark">
            <tr>
              {% for i in title %}
              <th scope="col">{{i}}</th>
              {% endfor %}
              <th>Operation</th>
            </tr>
          </thead>
          <tbody>
            {% for r in rows %}
              {% if r.status != "DONE" %}
              <tr>
                <th scope="row">{{r.priority}}</th>
                <td>{{r.name}}</td>
                <td>{{r.status}}</td>
                <td>{{r.story_point}}</td>
                <td>{{r.cumulative_story_point}}</td>
                <td>
                  <button onclick="window.location.href = 'http://127.0.0.1:8000/viewPBIdetail/{{ r.pk }}'; id = {{r.priority}}">Detail</button>
                  {% if r.status == "NOT_YET_START" or r.status == "UNFINISHED"%}
                  {%if r.status == "NOT_YET_START"%}
                    {% if user.is_authenticated and user.is_PRODUCT_OWNER %}
                      <button onclick="window.location.href = 'http://127.0.0.1:8000/updatePBI/{{ r.pk }}'; id = {{r.priority}}">Edit</button>
                      <button onclick="window.location.href = 'http://127.0.0.1:8000/deletePBI/{{ r.pk }}'; id = {{r.priority}}">Delete</button>
                    {% endif %}
                  {% endif %}
                    {% if product.sprint_status != "START"%}
                      {% if user.is_authenticated and user.is_DEVELOPER %}
                      <button onclick="window.location.href = 'http://127.0.0.1:8000/addtoSprint/{{ r.pk }}'; id = {{r.priority}}">Add to Sprint</button>
                      {% endif %}
                    {% endif %}
                  {% elif r.status == "IN_PROCESSING"%}
                    {% if product.sprint_status != "START"%}
                      {% if user.is_authenticated and user.is_DEVELOPER %}
                        <button onclick="window.location.href = 'http://127.0.0.1:8000/addtoSprint/{{ r.pk }}'; id = {{r.priority}}">Remove from Sprint</button>
                      {% endif %}
                    {% endif %}
                  {% endif %}
                </td>
              </tr>
              {% endif %}
            {% endfor %}
          </tbody>
        </table>

        {% if user.is_authenticated and user.is_PRODUCT_OWNER %}
        <p>
            <button class="btn btn-primary" onclick="window.location.href = 'http://127.0.0.1:8000/addPBI';">Add new PBI</button>
        </p>
        {% endif %}
      </div>
    </div>
    </div>
    <!-- /#page-content-wrapper -->
  </div>
  <!-- /#wrapper -->


  <!-- Bootstrap core JavaScript -->
  <script src= "{% static 'vendor/jquery/jquery.min.js' %}" ></script>
  <script src= "{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>

</body>

</html>

templates/po_reg_form.html
{% load static %}
<link href="{{ STATIC_URL }} https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css " rel="stylesheet" id="bootstrap-css">
<script src="{{ STATIC_URL }}static https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" ></script>
<script src="{{ STATIC_URL }} static https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="http://127.0.0.1:8000">Login <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

<section class="testimonial py-5" id="testimonial">
    <div class="container">
        <div class="row ">
            <div class="col-md-4 py-5 bg-primary text-white text-center ">
                <div class=" ">
                    <div class="card-body">
                        <img src="http://www.ansonika.com/mavia/img/registration_bg.svg" style="width:30%">
                        <h2 class="py-3">Register as A Product Owner</h2>
                        <p>Quickstep brings efficiency and accountability to tech while focusing
                           on delivering software and all exercises are designed around how a Scrum Team works to deliver that software.
                         </p>
                    </div>
                </div>
            </div>
            <div class="col-md-8 py-5 border">
                <h4 class="pb-4">Please fill with your details</h4>
                <form action="" method="post">
                  {% csrf_token %}
                  {{ form.as_p}}
                <button type="submit"> REGISTER </button>
              </form>
            </div>
        </div>
    </div>
</section>